[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas reporting
gas_reports = ["*"]

# Test configuration
test = "test"
cache_path = "cache"

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Formatter
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
